services:
- docker
language: go
sudo: required
before_install:
- sudo apt-get install bash
go:
- 1.6
before_install:
- echo -e "machine github.com\n login $GIT_TOKEN" >> ~/.netrc
- make deps
script:
- make lint
- make unit_test
notifications:
  slack:
    rooms:
      - 'intelsdi:k7XiVx2qAV7nCAMPXjRomNJ3'
    on_success: 'never'
    on_pull_requests: false
